"""Add AI copilot tables

Revision ID: c4a95565f41c
Revises: 011f3c16c051
Create Date: 2026-01-26 03:39:04.238804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a95565f41c'
down_revision: Union[str, Sequence[str], None] = '011f3c16c051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_context',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('activity_state', sa.Enum('IDLE', 'ACTIVE', 'FLOW_STATE', 'IN_FOCUS_MODE', name='useractivitystate'), nullable=True),
        sa.Column('is_in_focus_mode', sa.Boolean(), nullable=True),
        sa.Column('last_activity_at', sa.DateTime(), nullable=True),
        sa.Column('do_not_disturb_until', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('communication_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('message_id', sa.String(length=36), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('message_text', sa.Text(), nullable=False),
        sa.Column('tone_level', sa.String(length=20), nullable=True),
        sa.Column('status', sa.Enum('GENERATED', 'QUEUED', 'DELIVERED', 'DISMISSED', 'ACKNOWLEDGED', 'DEFERRED', name='messagestatus'), nullable=True),
        sa.Column('user_mood', sa.String(length=20), nullable=True),
        sa.Column('user_energy_level', sa.Integer(), nullable=True),
        sa.Column('generated_at', sa.DateTime(), nullable=True),
        sa.Column('delivered_at', sa.DateTime(), nullable=True),
        sa.Column('dismissed_at', sa.DateTime(), nullable=True),
        sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
        sa.Column('user_feedback', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('communication_events')
    op.drop_table('user_context')
    # ### end Alembic commands ###
